-- ─────────────────────────────────────────────────────────────────────────────
-- 009_fix_themes.sql
-- 1. Fixes industry name mismatches between themes and industries tables.
-- 2. Updates all theme tokens from zeach-theme-tokens.json (matched by name).
-- Run AFTER 007 + 008.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Fix industry name mismatches ──────────────────────────────────────────

UPDATE public.themes SET industry = 'Food & Beverage'       WHERE industry = 'Food & Delivery';
UPDATE public.themes SET industry = 'Retail & Fashion'      WHERE industry = 'E-commerce & Retail';
UPDATE public.themes SET industry = 'Education & Learning'  WHERE industry = 'Education';
UPDATE public.themes SET industry = 'Real Estate & Property' WHERE industry = 'Real Estate';
UPDATE public.themes SET industry = 'Finance & Banking'     WHERE industry = 'Finance';

-- ── 2. Update tokens from zeach-theme-tokens.json (matched by name) ──────────
-- Updates every row where name matches, regardless of industry.

UPDATE public.themes SET tokens = '{"primary": "#ec4899", "primary_light": "#fce7f3", "primary_dark": "#be185d", "secondary": "#f9a8d4", "accent": "#db2777", "background": "#fff5f7", "surface": "#ffffff", "surface2": "#fdf2f8", "border": "#fce7f3", "text": "#1e1b1e", "text_muted": "#9d8fa0", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Playfair Display", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Sakura';
UPDATE public.themes SET tokens = '{"primary": "#b8860b", "primary_light": "#fef9ee", "primary_dark": "#92680a", "secondary": "#d4af37", "accent": "#f5d060", "background": "#1a0a2e", "surface": "#2d1b4e", "surface2": "#3d2460", "border": "#4a2d6e", "text": "#f5f0e8", "text_muted": "#a89db8", "text_inverse": "#1a0a2e", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Cormorant", "body_font": "Nunito", "icon_weight": "sharp", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Luxe';
UPDATE public.themes SET tokens = '{"primary": "#16a34a", "primary_light": "#f0fdf4", "primary_dark": "#15803d", "secondary": "#86efac", "accent": "#22c55e", "background": "#f8fffe", "surface": "#ffffff", "surface2": "#f0fdf4", "border": "#dcfce7", "text": "#14231e", "text_muted": "#6b8f7a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Fresh';
UPDATE public.themes SET tokens = '{"primary": "#c0956f", "primary_light": "#fdf6f0", "primary_dark": "#a07050", "secondary": "#e8c9a8", "accent": "#d4a574", "background": "#fdf8f4", "surface": "#ffffff", "surface2": "#fdf0e8", "border": "#f5e0cc", "text": "#2c1810", "text_muted": "#9c7c6a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Glow';
UPDATE public.themes SET tokens = '{"primary": "#a78bfa", "primary_light": "#f5f3ff", "primary_dark": "#7c3aed", "secondary": "#ddd6fe", "accent": "#8b5cf6", "background": "#faf5ff", "surface": "#ffffff", "surface2": "#f5f3ff", "border": "#ede9fe", "text": "#1e1b2e", "text_muted": "#8b80a0", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Nunito", "body_font": "Nunito", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Petal';
UPDATE public.themes SET tokens = '{"primary": "#dc2626", "primary_light": "#fef2f2", "primary_dark": "#b91c1c", "secondary": "#fca5a5", "accent": "#f97316", "background": "#fffbf5", "surface": "#ffffff", "surface2": "#fff7ed", "border": "#fed7aa", "text": "#1c0a00", "text_muted": "#9a6a50", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Appetite';
UPDATE public.themes SET tokens = '{"primary": "#facc15", "primary_light": "#fefce8", "primary_dark": "#ca8a04", "secondary": "#fde68a", "accent": "#f97316", "background": "#0f0f0f", "surface": "#1a1a1a", "surface2": "#242424", "border": "#333333", "text": "#f5f5f5", "text_muted": "#a0a0a0", "text_inverse": "#0f0f0f", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Space Grotesk", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Street Food';
UPDATE public.themes SET tokens = '{"primary": "#65a30d", "primary_light": "#f7fee7", "primary_dark": "#4d7c0f", "secondary": "#bef264", "accent": "#84cc16", "background": "#f9fdf5", "surface": "#ffffff", "surface2": "#f1f8e9", "border": "#d9f0b0", "text": "#1a2e05", "text_muted": "#6b8a3e", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "DM Sans", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Fresh Market';
UPDATE public.themes SET tokens = '{"primary": "#92400e", "primary_light": "#fffbeb", "primary_dark": "#78350f", "secondary": "#d97706", "accent": "#b45309", "background": "#fdfaf6", "surface": "#ffffff", "surface2": "#fef9f0", "border": "#fde8c8", "text": "#1c1008", "text_muted": "#8c6a48", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Bistro';
UPDATE public.themes SET tokens = '{"primary": "#f59e0b", "primary_light": "#fffbeb", "primary_dark": "#d97706", "secondary": "#fcd34d", "accent": "#fb923c", "background": "#0a0a0a", "surface": "#141414", "surface2": "#1e1e1e", "border": "#2a2a2a", "text": "#f0f0f0", "text_muted": "#808080", "text_inverse": "#0a0a0a", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Dark Kitchen';
UPDATE public.themes SET tokens = '{"primary": "#2563eb", "primary_light": "#eff6ff", "primary_dark": "#1d4ed8", "secondary": "#93c5fd", "accent": "#3b82f6", "background": "#f8faff", "surface": "#ffffff", "surface2": "#f0f5ff", "border": "#e0eaff", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Clinical';
UPDATE public.themes SET tokens = '{"primary": "#0891b2", "primary_light": "#ecfeff", "primary_dark": "#0e7490", "secondary": "#a5f3fc", "accent": "#06b6d4", "background": "#f8fdff", "surface": "#ffffff", "surface2": "#f0faff", "border": "#cceeff", "text": "#0c2340", "text_muted": "#6b8fa8", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Nunito", "body_font": "Nunito", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Soft Care';
UPDATE public.themes SET tokens = '{"primary": "#14b8a6", "primary_light": "#f0fdfa", "primary_dark": "#0f766e", "secondary": "#5eead4", "accent": "#2dd4bf", "background": "#0f1923", "surface": "#162130", "surface2": "#1e2e40", "border": "#243848", "text": "#e2f0f8", "text_muted": "#7a9ab5", "text_inverse": "#0f1923", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist", "icon_weight": "outlined", "animation_speed": "fast", "animation_style": "smooth", "easing": "linear"}'::jsonb WHERE name = 'Modern Medical';
UPDATE public.themes SET tokens = '{"primary": "#4d7c5f", "primary_light": "#f0faf3", "primary_dark": "#3a5e47", "secondary": "#a7c4b0", "accent": "#6aab82", "background": "#f8fcf9", "surface": "#ffffff", "surface2": "#eef6f1", "border": "#d4ead9", "text": "#1a2e22", "text_muted": "#6b8a76", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "DM Sans", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Wellness';
UPDATE public.themes SET tokens = '{"primary": "#dc2626", "primary_light": "#fef2f2", "primary_dark": "#b91c1c", "secondary": "#fca5a5", "accent": "#ef4444", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f9f9f9", "border": "#e5e5e5", "text": "#0a0a0a", "text_muted": "#555555", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Emergency';
UPDATE public.themes SET tokens = '{"primary": "#b8860b", "primary_light": "#fef9ee", "primary_dark": "#92680a", "secondary": "#d4af37", "accent": "#f5d060", "background": "#0a0a0f", "surface": "#12121a", "surface2": "#1a1a26", "border": "#242433", "text": "#f0eefc", "text_muted": "#8080aa", "text_inverse": "#0a0a0f", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist", "icon_weight": "sharp", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Obsidian';
UPDATE public.themes SET tokens = '{"primary": "#2563eb", "primary_light": "#eff6ff", "primary_dark": "#1d4ed8", "secondary": "#93c5fd", "accent": "#3b82f6", "background": "#f8f9fc", "surface": "#ffffff", "surface2": "#f1f4f9", "border": "#e2e8f0", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Slate';
UPDATE public.themes SET tokens = '{"primary": "#0369a1", "primary_light": "#f0f9ff", "primary_dark": "#075985", "secondary": "#7dd3fc", "accent": "#0ea5e9", "background": "#f5f8fc", "surface": "#ffffff", "surface2": "#edf3f8", "border": "#d1e3f0", "text": "#0c1e2e", "text_muted": "#5a7a92", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Nordic';
UPDATE public.themes SET tokens = '{"primary": "#94a3b8", "primary_light": "#f8fafc", "primary_dark": "#64748b", "secondary": "#cbd5e1", "accent": "#e2e8f0", "background": "#0d1117", "surface": "#161b22", "surface2": "#21262d", "border": "#30363d", "text": "#f0f6fc", "text_muted": "#8b949e", "text_inverse": "#0d1117", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Space Grotesk", "icon_weight": "sharp", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Vault';
UPDATE public.themes SET tokens = '{"primary": "#059669", "primary_light": "#ecfdf5", "primary_dark": "#047857", "secondary": "#6ee7b7", "accent": "#10b981", "background": "#f5fffb", "surface": "#ffffff", "surface2": "#f0fdf8", "border": "#d1fae5", "text": "#052e20", "text_muted": "#4a7c6a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "DM Sans", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Mint';
UPDATE public.themes SET tokens = '{"primary": "#2563eb", "primary_light": "#eff6ff", "primary_dark": "#1d4ed8", "secondary": "#93c5fd", "accent": "#60a5fa", "background": "#f8faff", "surface": "#ffffff", "surface2": "#f0f5ff", "border": "#dbeafe", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Nunito", "body_font": "Nunito", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Campus';
UPDATE public.themes SET tokens = '{"primary": "#0f766e", "primary_light": "#f0fdfa", "primary_dark": "#0d5e57", "secondary": "#5eead4", "accent": "#14b8a6", "background": "#f8fcfb", "surface": "#ffffff", "surface2": "#f0faf8", "border": "#ccebe7", "text": "#0a2420", "text_muted": "#4d7872", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "outlined", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Scholar';
UPDATE public.themes SET tokens = '{"primary": "#f97316", "primary_light": "#fff7ed", "primary_dark": "#ea580c", "secondary": "#fbbf24", "accent": "#a855f7", "background": "#fffef5", "surface": "#ffffff", "surface2": "#fffae8", "border": "#fde68a", "text": "#1c0a00", "text_muted": "#8c6a3a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Nunito", "body_font": "Nunito", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Kids';
UPDATE public.themes SET tokens = '{"primary": "#18181b", "primary_light": "#f4f4f5", "primary_dark": "#09090b", "secondary": "#71717a", "accent": "#3f3f46", "background": "#ffffff", "surface": "#ffffff", "surface2": "#fafafa", "border": "#e4e4e7", "text": "#09090b", "text_muted": "#71717a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Focus';
UPDATE public.themes SET tokens = '{"primary": "#d4af37", "primary_light": "#fefce8", "primary_dark": "#a88c2c", "secondary": "#fde68a", "accent": "#f5d060", "background": "#0d0d14", "surface": "#141420", "surface2": "#1c1c2c", "border": "#282838", "text": "#f0eefc", "text_muted": "#8888aa", "text_inverse": "#0d0d14", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Cormorant", "body_font": "DM Sans", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Academy';
UPDATE public.themes SET tokens = '{"primary": "#f97316", "primary_light": "#fff7ed", "primary_dark": "#ea580c", "secondary": "#fb923c", "accent": "#f59e0b", "background": "#0a0a0a", "surface": "#141414", "surface2": "#1e1e1e", "border": "#2a2a2a", "text": "#f5f5f5", "text_muted": "#a0a0a0", "text_inverse": "#0a0a0a", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Wanderlust';
UPDATE public.themes SET tokens = '{"primary": "#c0956f", "primary_light": "#fdf6f0", "primary_dark": "#a07050", "secondary": "#e8c9a8", "accent": "#d4a574", "background": "#fdfaf6", "surface": "#ffffff", "surface2": "#fdf5ed", "border": "#f0dfc8", "text": "#2c1810", "text_muted": "#9c7c6a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Cormorant", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Resort';
UPDATE public.themes SET tokens = '{"primary": "#78350f", "primary_light": "#fef3c7", "primary_dark": "#5c2a0c", "secondary": "#92400e", "accent": "#d97706", "background": "#faf7f4", "surface": "#ffffff", "surface2": "#f5ede4", "border": "#e8d5c0", "text": "#1c0f00", "text_muted": "#7a5c40", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Adventure';
UPDATE public.themes SET tokens = '{"primary": "#1e293b", "primary_light": "#f8fafc", "primary_dark": "#0f172a", "secondary": "#475569", "accent": "#f97316", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f8fafc", "border": "#e2e8f0", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'City Guide';
UPDATE public.themes SET tokens = '{"primary": "#a08060", "primary_light": "#fdf8f4", "primary_dark": "#806040", "secondary": "#c8a888", "accent": "#b89070", "background": "#faf8f5", "surface": "#ffffff", "surface2": "#f5f0ea", "border": "#e8e0d5", "text": "#2a1e14", "text_muted": "#8a7060", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "DM Sans", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Nomad';
UPDATE public.themes SET tokens = '{"primary": "#5c6ac4", "primary_light": "#f4f5fa", "primary_dark": "#4959bd", "secondary": "#9da5d4", "accent": "#47c1bf", "background": "#f9fafb", "surface": "#ffffff", "surface2": "#f4f6f8", "border": "#e1e3e5", "text": "#212b36", "text_muted": "#637381", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Shopify Clean';
UPDATE public.themes SET tokens = '{"primary": "#000000", "primary_light": "#f5f5f5", "primary_dark": "#000000", "secondary": "#333333", "accent": "#c0a060", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f9f9f9", "border": "#e0e0e0", "text": "#000000", "text_muted": "#666666", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Cormorant", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Luxe Retail';
UPDATE public.themes SET tokens = '{"primary": "#b45309", "primary_light": "#fffbeb", "primary_dark": "#92400e", "secondary": "#d97706", "accent": "#f59e0b", "background": "#fdfaf5", "surface": "#ffffff", "surface2": "#fef8ee", "border": "#fde8c0", "text": "#1c0f00", "text_muted": "#8c6a3a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Warm Market';
UPDATE public.themes SET tokens = '{"primary": "#dc2626", "primary_light": "#fef2f2", "primary_dark": "#b91c1c", "secondary": "#fca5a5", "accent": "#facc15", "background": "#ffffff", "surface": "#ffffff", "surface2": "#fef2f2", "border": "#fecaca", "text": "#0a0a0a", "text_muted": "#555555", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Flash Sale';
UPDATE public.themes SET tokens = '{"primary": "#be8a9d", "primary_light": "#fdf4f6", "primary_dark": "#9e6a7d", "secondary": "#e8c4ce", "accent": "#d4a0b0", "background": "#fdf8f9", "surface": "#ffffff", "surface2": "#faf0f3", "border": "#f5e0e5", "text": "#2a1018", "text_muted": "#9a7080", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Playfair Display", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Boutique';
UPDATE public.themes SET tokens = '{"primary": "#2563eb", "primary_light": "#eff6ff", "primary_dark": "#1d4ed8", "secondary": "#93c5fd", "accent": "#06b6d4", "background": "#f8faff", "surface": "#ffffff", "surface2": "#f0f5ff", "border": "#dbeafe", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Nunito", "body_font": "Nunito", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Connect';
UPDATE public.themes SET tokens = '{"primary": "#a855f7", "primary_light": "#faf5ff", "primary_dark": "#9333ea", "secondary": "#d8b4fe", "accent": "#ec4899", "background": "#09090b", "surface": "#111113", "surface2": "#18181b", "border": "#27272a", "text": "#fafafa", "text_muted": "#a1a1aa", "text_inverse": "#09090b", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Dark Social';
UPDATE public.themes SET tokens = '{"primary": "#d97706", "primary_light": "#fffbeb", "primary_dark": "#b45309", "secondary": "#fcd34d", "accent": "#f59e0b", "background": "#fffdf8", "surface": "#ffffff", "surface2": "#fef9ec", "border": "#fde68a", "text": "#1c0f00", "text_muted": "#8c6a3a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "DM Sans", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Warm Community';
UPDATE public.themes SET tokens = '{"primary": "#6366f1", "primary_light": "#eef2ff", "primary_dark": "#4f46e5", "secondary": "#a5b4fc", "accent": "#ec4899", "background": "#0f0f14", "surface": "#16161e", "surface2": "#1e1e2e", "border": "#282838", "text": "#f0eeff", "text_muted": "#8888bb", "text_inverse": "#0f0f14", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "smooth", "easing": "spring"}'::jsonb WHERE name = 'Creator';
UPDATE public.themes SET tokens = '{"primary": "#ff6600", "primary_light": "#fff7f0", "primary_dark": "#cc5200", "secondary": "#ffab80", "accent": "#ff8533", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f6f6ef", "border": "#e8e8e0", "text": "#000000", "text_muted": "#828282", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Forum';
UPDATE public.themes SET tokens = '{"primary": "#facc15", "primary_light": "#fefce8", "primary_dark": "#eab308", "secondary": "#fde68a", "accent": "#f97316", "background": "#0a0a0a", "surface": "#111111", "surface2": "#1a1a1a", "border": "#2a2a2a", "text": "#f5f5f5", "text_muted": "#a0a0a0", "text_inverse": "#0a0a0a", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Space Grotesk", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Power';
UPDATE public.themes SET tokens = '{"primary": "#2563eb", "primary_light": "#eff6ff", "primary_dark": "#1d4ed8", "secondary": "#60a5fa", "accent": "#0ea5e9", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f8faff", "border": "#e0eaff", "text": "#0a0a14", "text_muted": "#5a6a8a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Athletic';
UPDATE public.themes SET tokens = '{"primary": "#4d7c5f", "primary_light": "#f0faf3", "primary_dark": "#3a5e47", "secondary": "#a7c4b0", "accent": "#6aab82", "background": "#f8fcf9", "surface": "#ffffff", "surface2": "#eef6f1", "border": "#d4ead9", "text": "#1a2e22", "text_muted": "#6b8a76", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "DM Sans", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Zen';
UPDATE public.themes SET tokens = '{"primary": "#dc2626", "primary_light": "#fef2f2", "primary_dark": "#b91c1c", "secondary": "#fca5a5", "accent": "#f97316", "background": "#0a0505", "surface": "#140a0a", "surface2": "#1e1010", "border": "#2e1818", "text": "#f5f0f0", "text_muted": "#a08080", "text_inverse": "#0a0505", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "Space Grotesk", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Gains';
UPDATE public.themes SET tokens = '{"primary": "#0ea5e9", "primary_light": "#f0f9ff", "primary_dark": "#0284c7", "secondary": "#7dd3fc", "accent": "#06b6d4", "background": "#0a0f14", "surface": "#111820", "surface2": "#18232e", "border": "#1e2e3e", "text": "#e2f0f8", "text_muted": "#6a8fa8", "text_inverse": "#0a0f14", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist Mono", "icon_weight": "outlined", "animation_speed": "fast", "animation_style": "smooth", "easing": "linear"}'::jsonb WHERE name = 'Track';
UPDATE public.themes SET tokens = '{"primary": "#b8860b", "primary_light": "#fef9ee", "primary_dark": "#92680a", "secondary": "#d4af37", "accent": "#c8a040", "background": "#0c1018", "surface": "#141c28", "surface2": "#1c2838", "border": "#243048", "text": "#f0eefc", "text_muted": "#8088a8", "text_inverse": "#0c1018", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Cormorant", "body_font": "DM Sans", "icon_weight": "outlined", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Estate';
UPDATE public.themes SET tokens = '{"primary": "#334155", "primary_light": "#f8fafc", "primary_dark": "#1e293b", "secondary": "#64748b", "accent": "#0ea5e9", "background": "#f8fafc", "surface": "#ffffff", "surface2": "#f1f5f9", "border": "#e2e8f0", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Modern Property';
UPDATE public.themes SET tokens = '{"primary": "#c2714f", "primary_light": "#fdf4f0", "primary_dark": "#a05030", "secondary": "#e8a888", "accent": "#d4845e", "background": "#fdf8f4", "surface": "#ffffff", "surface2": "#faf2ec", "border": "#f0ddd0", "text": "#2c1408", "text_muted": "#9c7060", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Warm Home';
UPDATE public.themes SET tokens = '{"primary": "#475569", "primary_light": "#f8fafc", "primary_dark": "#334155", "secondary": "#94a3b8", "accent": "#f97316", "background": "#0f0f0f", "surface": "#1a1a1a", "surface2": "#242424", "border": "#333333", "text": "#f5f5f5", "text_muted": "#888888", "text_inverse": "#0f0f0f", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Urban';
UPDATE public.themes SET tokens = '{"primary": "#c0c0c0", "primary_light": "#f8f8f8", "primary_dark": "#a0a0a0", "secondary": "#e0e0e0", "accent": "#d4af37", "background": "#000000", "surface": "#080808", "surface2": "#101010", "border": "#181818", "text": "#f8f8f8", "text_muted": "#888888", "text_inverse": "#000000", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist", "icon_weight": "sharp", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Luxury';
UPDATE public.themes SET tokens = '{"primary": "#000000", "primary_light": "#f5f5f5", "primary_dark": "#000000", "secondary": "#333333", "accent": "#2563eb", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f5f5f5", "border": "#e0e0e0", "text": "#000000", "text_muted": "#666666", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Drive';
UPDATE public.themes SET tokens = '{"primary": "#1e40af", "primary_light": "#eff6ff", "primary_dark": "#1e3a8a", "secondary": "#64748b", "accent": "#f59e0b", "background": "#0f1520", "surface": "#161e2e", "surface2": "#1e2a3e", "border": "#28384e", "text": "#e0e8f0", "text_muted": "#6080a0", "text_inverse": "#0f1520", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Inter", "icon_weight": "sharp", "animation_speed": "medium", "animation_style": "smooth", "easing": "linear"}'::jsonb WHERE name = 'Fleet';
UPDATE public.themes SET tokens = '{"primary": "#f97316", "primary_light": "#fff7ed", "primary_dark": "#ea580c", "secondary": "#fb923c", "accent": "#facc15", "background": "#ffffff", "surface": "#ffffff", "surface2": "#fff7f0", "border": "#fed7aa", "text": "#0a0a0a", "text_muted": "#555555", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Speed';
UPDATE public.themes SET tokens = '{"primary": "#16a34a", "primary_light": "#f0fdf4", "primary_dark": "#15803d", "secondary": "#86efac", "accent": "#0ea5e9", "background": "#f8fffe", "surface": "#ffffff", "surface2": "#f0fdf4", "border": "#dcfce7", "text": "#052e16", "text_muted": "#4a7a5a", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "DM Sans", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Route';
UPDATE public.themes SET tokens = '{"primary": "#78350f", "primary_light": "#fef3c7", "primary_dark": "#5c2a0c", "secondary": "#d97706", "accent": "#f59e0b", "background": "#080808", "surface": "#121212", "surface2": "#1c1c1c", "border": "#2a2a2a", "text": "#f0ece0", "text_muted": "#8a8070", "text_inverse": "#080808", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Space Grotesk", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Cargo';
UPDATE public.themes SET tokens = '{"primary": "#5e6ad2", "primary_light": "#eef0ff", "primary_dark": "#4a54c0", "secondary": "#9da3e8", "accent": "#7c85e0", "background": "#0f0f12", "surface": "#16161a", "surface2": "#1c1c22", "border": "#282830", "text": "#f0f0f8", "text_muted": "#6868a0", "text_inverse": "#0f0f12", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "ease-out"}'::jsonb WHERE name = 'Linear';
UPDATE public.themes SET tokens = '{"primary": "#2e2e2e", "primary_light": "#f7f6f3", "primary_dark": "#1a1a1a", "secondary": "#6b6b6b", "accent": "#2383e2", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f7f6f3", "border": "#e9e9e7", "text": "#2e2e2e", "text_muted": "#9b9b9b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Notion';
UPDATE public.themes SET tokens = '{"primary": "#4f46e5", "primary_light": "#eef2ff", "primary_dark": "#4338ca", "secondary": "#818cf8", "accent": "#06b6d4", "background": "#0f172a", "surface": "#1e293b", "surface2": "#273548", "border": "#334155", "text": "#f1f5f9", "text_muted": "#64748b", "text_inverse": "#0f172a", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "linear"}'::jsonb WHERE name = 'Dashboard';
UPDATE public.themes SET tokens = '{"primary": "#10b981", "primary_light": "#ecfdf5", "primary_dark": "#059669", "secondary": "#6ee7b7", "accent": "#06b6d4", "background": "#000000", "surface": "#0a0a0a", "surface2": "#111111", "border": "#1a1a1a", "text": "#00ff88", "text_muted": "#006633", "text_inverse": "#000000", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist Mono", "body_font": "Geist Mono", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Command';
UPDATE public.themes SET tokens = '{"primary": "#3b82f6", "primary_light": "#eff6ff", "primary_dark": "#2563eb", "secondary": "#93c5fd", "accent": "#6366f1", "background": "#030712", "surface": "#0a0f1e", "surface2": "#111827", "border": "#1f2937", "text": "#f9fafb", "text_muted": "#6b7280", "text_inverse": "#030712", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Neural';
UPDATE public.themes SET tokens = '{"primary": "#2563eb", "primary_light": "#eff6ff", "primary_dark": "#1d4ed8", "secondary": "#93c5fd", "accent": "#6366f1", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f8faff", "border": "#e0eaff", "text": "#0a0f1e", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Clarity';
UPDATE public.themes SET tokens = '{"primary": "#00ff41", "primary_light": "#f0fff4", "primary_dark": "#00cc33", "secondary": "#00cc33", "accent": "#00ffaa", "background": "#000000", "surface": "#0a0a0a", "surface2": "#111111", "border": "#1a1a1a", "text": "#00ff41", "text_muted": "#007a1f", "text_inverse": "#000000", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Courier Prime", "body_font": "Courier Prime", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Terminal';
UPDATE public.themes SET tokens = '{"primary": "#7c3aed", "primary_light": "#faf5ff", "primary_dark": "#6d28d9", "secondary": "#a78bfa", "accent": "#ec4899", "background": "#0f0a1a", "surface": "#18102a", "surface2": "#22183a", "border": "#2e2048", "text": "#faf5ff", "text_muted": "#9080b8", "text_inverse": "#0f0a1a", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "smooth", "easing": "spring"}'::jsonb WHERE name = 'Gradient';
UPDATE public.themes SET tokens = '{"primary": "#06b6d4", "primary_light": "#ecfeff", "primary_dark": "#0891b2", "secondary": "#67e8f9", "accent": "#22d3ee", "background": "#030f14", "surface": "#071820", "surface2": "#0e2430", "border": "#143040", "text": "#ecfeff", "text_muted": "#4a8fa8", "text_inverse": "#030f14", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Space Grotesk", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "smooth", "easing": "linear"}'::jsonb WHERE name = 'Pulse';
UPDATE public.themes SET tokens = '{"primary": "#569cd6", "primary_light": "#1e3a5f", "primary_dark": "#4080b0", "secondary": "#9cdcfe", "accent": "#4ec9b0", "background": "#1e1e1e", "surface": "#252526", "surface2": "#2d2d30", "border": "#3e3e42", "text": "#d4d4d4", "text_muted": "#808080", "text_inverse": "#1e1e1e", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist Mono", "icon_weight": "outlined", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'IDE';
UPDATE public.themes SET tokens = '{"primary": "#2563eb", "primary_light": "#eff6ff", "primary_dark": "#1d4ed8", "secondary": "#93c5fd", "accent": "#6366f1", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f8fafc", "border": "#e2e8f0", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Docs';
UPDATE public.themes SET tokens = '{"primary": "#10b981", "primary_light": "#ecfdf5", "primary_dark": "#059669", "secondary": "#6ee7b7", "accent": "#06b6d4", "background": "#0a0f0a", "surface": "#111811", "surface2": "#182018", "border": "#1e2e1e", "text": "#ecfdf5", "text_muted": "#4a8a5a", "text_inverse": "#0a0f0a", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Geist", "body_font": "Geist Mono", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'API';
UPDATE public.themes SET tokens = '{"primary": "#ef4444", "primary_light": "#fef2f2", "primary_dark": "#dc2626", "secondary": "#fca5a5", "accent": "#f97316", "background": "#0f0808", "surface": "#1a1010", "surface2": "#221818", "border": "#2e2020", "text": "#fef2f2", "text_muted": "#a07070", "text_inverse": "#0f0808", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Geist Mono", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "linear"}'::jsonb WHERE name = 'Debug';
UPDATE public.themes SET tokens = '{"primary": "#e50914", "primary_light": "#fef2f2", "primary_dark": "#b8070f", "secondary": "#ff4d55", "accent": "#e50914", "background": "#141414", "surface": "#1f1f1f", "surface2": "#2a2a2a", "border": "#333333", "text": "#ffffff", "text_muted": "#aaaaaa", "text_inverse": "#141414", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Stream';
UPDATE public.themes SET tokens = '{"primary": "#8b5cf6", "primary_light": "#faf5ff", "primary_dark": "#7c3aed", "secondary": "#c4b5fd", "accent": "#a78bfa", "background": "#1c1520", "surface": "#26202e", "surface2": "#302838", "border": "#3e3048", "text": "#f5f0fc", "text_muted": "#8870a8", "text_inverse": "#1c1520", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Podcast';
UPDATE public.themes SET tokens = '{"primary": "#a855f7", "primary_light": "#faf5ff", "primary_dark": "#9333ea", "secondary": "#06b6d4", "accent": "#10b981", "background": "#050010", "surface": "#0a0820", "surface2": "#100f2e", "border": "#1a1840", "text": "#f0eeff", "text_muted": "#6060aa", "text_inverse": "#050010", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "Space Grotesk", "icon_weight": "sharp", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Gaming';
UPDATE public.themes SET tokens = '{"primary": "#1e293b", "primary_light": "#f8fafc", "primary_dark": "#0f172a", "secondary": "#475569", "accent": "#dc2626", "background": "#ffffff", "surface": "#ffffff", "surface2": "#f8f8f8", "border": "#e0e0e0", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Cormorant", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Magazine';
UPDATE public.themes SET tokens = '{"primary": "#d4af37", "primary_light": "#fefce8", "primary_dark": "#a88c2c", "secondary": "#f5d060", "accent": "#fbbf24", "background": "#000000", "surface": "#0a0a0a", "surface2": "#141414", "border": "#1e1e1e", "text": "#f5f5f5", "text_muted": "#888888", "text_inverse": "#000000", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Playfair Display", "body_font": "DM Sans", "icon_weight": "sharp", "animation_speed": "slow", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Spotlight';
UPDATE public.themes SET tokens = '{"primary": "#f5d060", "primary_light": "#fefce8", "primary_dark": "#d4af37", "secondary": "#fbbf24", "accent": "#f97316", "background": "#000000", "surface": "#0d0d0d", "surface2": "#1a1a1a", "border": "#252525", "text": "#f5f5f5", "text_muted": "#909090", "text_inverse": "#000000", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "sharp", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Stage';
UPDATE public.themes SET tokens = '{"primary": "#f97316", "primary_light": "#fff7ed", "primary_dark": "#ea580c", "secondary": "#facc15", "accent": "#a855f7", "background": "#0a0008", "surface": "#140010", "surface2": "#1e0018", "border": "#2e0028", "text": "#fff0fe", "text_muted": "#a060a0", "text_inverse": "#0a0008", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "Syne", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Festival';
UPDATE public.themes SET tokens = '{"primary": "#1e40af", "primary_light": "#eff6ff", "primary_dark": "#1e3a8a", "secondary": "#93c5fd", "accent": "#0ea5e9", "background": "#f8fafc", "surface": "#ffffff", "surface2": "#f1f5f9", "border": "#e2e8f0", "text": "#0f172a", "text_muted": "#64748b", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Inter", "body_font": "Inter", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Corporate Event';
UPDATE public.themes SET tokens = '{"primary": "#ec4899", "primary_light": "#fdf2f8", "primary_dark": "#db2777", "secondary": "#a855f7", "accent": "#06b6d4", "background": "#080010", "surface": "#100020", "surface2": "#180030", "border": "#240048", "text": "#fdf0ff", "text_muted": "#9060b0", "text_inverse": "#080010", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "fast", "animation_style": "snappy", "easing": "spring"}'::jsonb WHERE name = 'Party';
UPDATE public.themes SET tokens = '{"primary": "#92400e", "primary_light": "#fffbeb", "primary_dark": "#78350f", "secondary": "#d97706", "accent": "#b45309", "background": "#fdfaf6", "surface": "#ffffff", "surface2": "#fef9f0", "border": "#fde8c8", "text": "#1c1008", "text_muted": "#8c6a48", "text_inverse": "#ffffff", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Intimate';
UPDATE public.themes SET tokens = '{"primary": "#06b6d4", "primary_light": "#ecfeff", "primary_dark": "#0891b2", "secondary": "#67e8f9", "accent": "#22d3ee", "background": "#050505", "surface": "#0a0a0a", "surface2": "#111111", "border": "#1a1a1a", "text": "#f0feff", "text_muted": "#4a8090", "text_inverse": "#050505", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Space Grotesk", "body_font": "DM Sans", "icon_weight": "sharp", "animation_speed": "medium", "animation_style": "smooth", "easing": "ease-out"}'::jsonb WHERE name = 'Noir';
UPDATE public.themes SET tokens = '{"primary": "#a78bfa", "primary_light": "#f5f3ff", "primary_dark": "#7c3aed", "secondary": "#c4b5fd", "accent": "#ec4899", "background": "#0f0c29", "surface": "rgba(255,255,255,0.06)", "surface2": "rgba(255,255,255,0.1)", "border": "rgba(255,255,255,0.15)", "text": "#ffffff", "text_muted": "rgba(255,255,255,0.5)", "text_inverse": "#0f0c29", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Syne", "body_font": "DM Sans", "icon_weight": "rounded", "animation_speed": "slow", "animation_style": "smooth", "easing": "spring"}'::jsonb WHERE name = 'Aurora';
UPDATE public.themes SET tokens = '{"primary": "#292524", "primary_light": "#fafaf8", "primary_dark": "#1c1917", "secondary": "#78716c", "accent": "#a8a29e", "background": "#fafaf8", "surface": "#ffffff", "surface2": "#f5f4f0", "border": "#e7e5e4", "text": "#1c1917", "text_muted": "#78716c", "text_inverse": "#fafaf8", "success": "#10b981", "error": "#ef4444", "warning": "#f59e0b", "heading_font": "Lora", "body_font": "DM Sans", "icon_weight": "outlined", "animation_speed": "medium", "animation_style": "gentle", "easing": "spring"}'::jsonb WHERE name = 'Paper';
